spring:
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASSWORD}
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    platform: postgresql
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 60000

rabbitmq-queue-name: ${RABBIT_QUEUE_NAME}